### ISSUE TITLE
Files hierarchy issue in linux

### ISSUE THREAD

**Issue by peylight** [ArKaNeMaN/amxx-VipModular-pub#6]
Hello,
When i extract your zip release file in the linux os i see file path as name of file.
I mean if for example the real file name is DisablePlugins.json i can see RandomWeaponsWarmUP\addons\amxmodx\configs\plugins\RWW\DisablePlugins.json for name of file.
In linux the path of files using slash (/) should be like and your file shoud be like RandomWeaponsWarmUP/addons/amxmodx/configs/plugins/RWW/DisablePlugins.json
However you shouldn't use the name of file as path of file.
So please fix it.

**Comment by ArKaNeMaN** [comment]
This problem is actual for all projects with my build script. I will try to fix it a bit later.
Thx for bug report :)

**Comment by ArKaNeMaN** [comment]
@peylight Try this archive, pls. [VipModular.zip](https://github.com/ArKaNeMaN/amxx-VipModular-pub/files/13521113/VipModular.zip)

**Comment by peylight** [comment]
@ArKaNeMaN Thanks, it is fixed.
